name: Update version.ts from pxt.json

on:
  push:
    branches:
      - main  # oder dein Hauptbranch

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run update-version script
        run: |
          npm install
          node update-version.js

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.ts
          git diff --cached --quiet || git commit -m "🔄 Update version.ts from pxt.json"
          git push
