name: Update version.ts on push

on:
  release:
    types:[create]

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get version from pxt.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./pxt.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run update-version script
        run: node update-version.js

      - name: Commit version.ts if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.ts
          git diff --cached --quiet || git commit -m "Auto-update version.ts from pxt.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master

      - name: Force-push tag with version from pxt.json
        run: |
          git fetch --tags
          git tag -d v${{ steps.get_version.outputs.version }} || true
          git tag v${{ steps.get_version.outputs.version }}
          git push --force origin v${{ steps.get_version.outputs.version }}
